### ISSUE TITLE
Support None as fallback locale

### ISSUE THREAD

**Issue by ZRunner** [Krutyi-4el/i18nice#17]
Hi!

I've noticed a weird recursion error when using your improved version of python-i18n (I love what you did btw, thanks for the work).
Basically, in the `t` function, when a translation key cannot be found, your code checks if the used language is the same as the fallback one. If not, then it tries to find the translation with the fallback language. And that works fine as long as you *do* have a fallback language.

https://github.com/Krutyi-4el/i18nice/blob/7579c9da684f362ded7fa0acab7379098e539881/i18n/translator.py#L12-L21

BUT if the fallback language is set to `None`, then the condition at line 20 is always met (because `locale` cannot be None), and `t()` is called back with `locale=None`, which forces to use the `locale` config value, which is again different than the fallback value.

A simple fix should be to check if `config.get('fallback')` is None, and if it is, raise a proper error (a KeyError or anything more intuitive).

Hope this helps!

**Comment by Krutyi-4el** [comment]
Thanks for the feedback!

In fact, `fallback` was never designed to be `None`, but I think it makes sense to add this feature. Will do in the next update.

**Comment by ZRunner** [comment]
Makes sense. Thanks for considering adding support to it then.

FYI I use None as fallback configuration because I want to receive an error if the translation is missing for any language I use. If I'm right, this is the only way (or will be?) to get a KeyError immediately, and don't... well, don't fall back to another working language.

**Comment by Krutyi-4el** [comment]
You are *almost* right. You still won't avoid `search_translation()` which is terribly slow because of directory scanning (btw, it should be easy to change this as we have `load_everything()` now). I don't recommend relying on missing transactions in the first place. Of course, it's ok for debugging.

**Comment by Krutyi-4el** [comment]
The new release is out
