### ISSUE TITLE
Add `py.typed` marker to work with PEP 561

### ISSUE THREAD

**Issue by zyf722** [Krutyi-4el/i18nice#23]
The project currently lacks a py.typed marker file, which is required to declare the project as [PEP 561](https://peps.python.org/pep-0561/#packaging-type-information) compliant. This file is essential for proper type checking and type hinting support when the project is used as a dependency in other Python packages.

An empty `py.typed` marker file could be added to the project's root directory, along with one line change in `setup.py`. This shall enable type checkers and IDEs to recognize the project as a valid type hint provider.

**Comment by Krutyi-4el** [comment]
You're right, thanks. I'll add it soon.

**Comment by Krutyi-4el** [comment]
The new release (0.11.0) have `py.typed` included.
