### ISSUE TITLE
regression: ValueError exception when %% is used in string

### ISSUE THREAD

**Issue by umaplehurst** [Krutyi-4el/i18nice#25]
Many thanks for your work on this library!
I have found a small regression since when static references were introduced.

Steps to reproduce:

a) `i18n.set("on_missing_placeholder", "error")`
b) have a translation string in a .yml with "%%" such as the following: `Hello world ! %% %{xyz}`
c) a `ValueError` from Python is then raised when trying to use `i18n.t` -- it looks like the problem is that `%%` gets converted to `%` during `expand_static_refs` in `formatters.py`

Героям слава!

**Comment by Krutyi-4el** [comment]
Thank you for the report. This is indeed a bug.
