### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheHellTower** [Krutyi-4el/i18nice#29]
Hello,

I wanted to know, can we add a folder of translation then do for example:

```js
message.translate("Administration:LANGUAGES_LIST", message.guild.id, { LANGUAGES:  languages.join("\n- ") })
```

See: [this](https://github.com/TheHellTower/Discord.JS-v14-Bot-Boilerplate/blob/main/src/Languages/en-US/Administration.json#L8) & [this](https://github.com/TheHellTower/Discord.JS-v14-Bot-Boilerplate/blob/main/src/Commands/Administration/Language.js#L27C22-L27C136) and [this](github.com/TheHellTower/Discord.JS-v14-Bot-Boilerplate/blob/main/src/Helpers/Extenders.js#L4) for example(`JavaScript example but I mean it for this module in Python`)

Best Regards.

**Comment by Krutyi-4el** [comment]
Yes, it is possible, but you'll need a different syntax for placeholders.

**Comment by TheHellTower** [comment]
> Yes, it is possible, but you'll need a different syntax for placeholders.

Could you make me a small example ?

**Comment by Krutyi-4el** [comment]
Oh, now I see that your directory structure is a bit unusual for this library.
However, you can use a workaround like this:
```python
import i18n

i18n.load_path.append("src/Languages")
i18n.set("file_format", "json")
i18n.set("filename_format", "{namespace}.{format}")
i18n.set("namespace_delimiter", ":")
i18n.set("skip_locale_root_data", True)

def translate(key, locale, **kwargs):
    return i18n.t(f"{locale}:{key}", **kwargs)

print(translate("Administration:LANGUAGES_LIST", "en-US", LANGUAGES="..."))
```
Placeholders in the JSON needs to be converted too. Example: `{{LANGUAGES}}` becomes `%{LANGUAGES}`.

**Comment by TheHellTower** [comment]
> Oh, now I see that your directory structure is a bit unusual for this library. However, you can use a workaround like this:
> 
> ```python
> import i18n
> 
> i18n.load_path.append("src/Languages")
> i18n.set("file_format", "json")
> i18n.set("filename_format", "{namespace}.{format}")
> i18n.set("namespace_delimiter", ":")
> i18n.set("skip_locale_root_data", True)
> 
> def translate(key, locale, **kwargs):
>     return i18n.t(f"{locale}:{key}", **kwargs)
> 
> print(translate("Administration:LANGUAGES_LIST", "en-US", LANGUAGES="..."))
> ```
> 
> Placeholders in the JSON needs to be converted too. Example: `{{LANGUAGES}}` becomes `%{LANGUAGES}`.

Thanks a lot ! I'll try that as soon as I can !

**Comment by Krutyi-4el** [comment]
I've added a setting to properly support directory structure like yours.

You can read about it [here](https://github.com/Krutyi-4el/i18nice/tree/v0.12.0#different-directory-structure).

**Comment by TheHellTower** [comment]
> I've added a setting to properly support directory structure like yours.
> 
> You can read about it [here](https://github.com/Krutyi-4el/i18nice/tree/v0.12.0#different-directory-structure).

Not being a Python user I'm a bit lost, what would be your advice to use the i18n translations over files ?
Is there a way to make it global for example ?

**Comment by Krutyi-4el** [comment]
Can you elaborate on your question? Files are ok and this library has only global state, no per-object translations or something like that, so I don't understand your point.

**Comment by TheHellTower** [comment]
> Can you elaborate on your question? Files are ok and this library has only global state, no per-object translations or something like that, so I don't understand your point.

I just had to import i18n in other files to use it, I wasn't sure if it would work.. But everything work like a charm there now !
