### ISSUE TITLE
conda recipe for i18nice

### ISSUE THREAD

**Issue by cmarmo** [Krutyi-4el/i18nice#31]
Hi @Krutyi-4el,

I have recently switched to `i18nice` from `python-i18n`.
Everything is working fine, thank you for keeping the project alive.

Now, I would like to produce a conda recipe for the project I'm working on: as all the dependencies should be available on a conda channel, I am planning to create a recipe for `i18nice` too.

I am opening this issue to check whether you are ok with that.
Let me know!

Thanks for your attention! :pray:

**Comment by Krutyi-4el** [comment]
Thank you for the feedback.

Is a "recipe" just a bunch of files necessary to build the package? I'm ok with that, however, if it can be incorporated into this repository, I'd be grateful for a pull request.

**Comment by cmarmo** [comment]
Thanks for your answer!
You already did the hard work of packaging for pypi, so the conda recipe will be a yaml file that can be automatically generated from the pypi package (using eg [grayskull](https://conda.github.io/grayskull/)).
The recipe should then be added to the [conda-forge feedstocks](https://github.com/conda-forge/feedstocks).

There is no need to include the recipe in the main repo: it might be useful to add a conda (and pypi) badge to the readme once the package is available in the feedstocks... I can offer a pull request at that time.

Do you agree with this plan?

**Comment by Krutyi-4el** [comment]
I see, that sounds great 👍
